apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agones-games
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: agones-games
      #finalizers:
        # This finalizer is for demo purposes, in production remove apps using argocd CLI "argocd app delete workload --cascade"
        # When you invoke argocd app delete with --cascade, the finalizer is added automatically.
      #  - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.workload_repo_url}}'
          targetRevision: '{{metadata.annotations.workload_repo_revision}}'
          path: '{{metadata.annotations.workload_repo_basepath}}{{metadata.annotations.workload_repo_path}}/agones/games'
      destination:
        name: '{{name}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
        retry:
          backoff:
            duration: 1m
          limit: 60